// Shared test fixture: a minimal **valid** `TikTokExport` (10 categories, required keys, empty
// encodings everywhere). Typed `TikTokExport` → checked against the contract at compile time. Single
// home (consumed by validate.test.ts and pipeline.test.ts); not exported from `index.ts` (test-only,
// tree-shaken from the app). Factory: returns a fresh object on each call (mutable on the test side
// after a cast).

import type { TikTokExport } from './tiktok-export';

/** Minimal valid TikTok export — empty encodings everywhere (a contract-conformant case). */
export function validTikTokExport(): TikTokExport {
  return {
    Comment: { Comments: { App: 0, CommentsList: [] } },
    'Direct Message': {
      'Direct Messages': { ChatHistory: {} },
      'Group Chat': { GroupChat: {} },
      'Tako Chat History': { TakoChatHistoryList: [] },
    },
    'Income+ Wallet': {
      'Coin Purchase History': { CoinPurchaseHistoryList: [] },
      'Transaction History': { TransactionsList: null },
    },
    'Likes and Favorites': {
      Collection: {},
      'Favorite Collection': { FavoriteCollectionList: [] },
      'Favorite Comment': { FavoriteCommentList: [] },
      'Favorite Drama': {},
      'Favorite Effects': { FavoriteEffectsList: [] },
      'Favorite Hashtags': { FavoriteHashtagList: [] },
      'Favorite Location': { FavoriteLocationList: [] },
      'Favorite Movies and TV': { FavoriteMoviesAndTVList: [] },
      'Favorite Playlists': { FavoritePlaylistList: [] },
      'Favorite Sounds': { FavoriteSoundList: [] },
      'Favorite Videos': { App: 0, FavoriteVideoList: [] },
      'Like List': { App: 0, ItemFavoriteList: [] },
    },
    'Location Review': { 'Location Reviews': { ReviewsList: null } },
    Post: {
      Posts: { VideoList: null },
      'Recently Deleted Posts': { PostList: [] },
      Story: {},
    },
    'Profile And Settings': {
      'AI-Moji': { CreateDate: '', AIMojiList: null },
      AISelfImage: {},
      Autofill: {
        PhoneNumber: '',
        Email: '',
        FirstName: '',
        LastName: '',
        Address: '',
        ZipCode: '',
        Unit: '',
        City: '',
        State: '',
        Country: '',
      },
      'Block List': { App: 0, BlockList: null },
      Follower: { App: 0, IsFastLane: false, FansList: [] },
      Following: { App: 0, IsFastLane: false, Following: [] },
      'Off TikTok Activity': { OffTikTokActivityDataList: null },
      'Profile Info': {
        App: 0,
        ProfileMap: {
          PlatformInfo: [],
          accountRegion: '',
          aiSelf: '',
          bioDescription: '',
          birthDate: '',
          displayName: '',
          emailAddress: '',
          followerCount: 0,
          followingCount: 0,
          fundraiser: '',
          inferredGender: '',
          instagramLink: '',
          lemon8Link: '',
          likesReceived: '',
          profilePhoto: '',
          profileVideo: '',
          telephoneNumber: '',
          userName: '',
          youtubeLink: '',
        },
      },
      ProfileViews: { ProfileViewList: null },
      Settings: { App: 0, SettingsMap: {} },
    },
    'TikTok Live': {
      'Go Live History': { GoLiveList: null },
      'Go Live Settings': { SettingsMap: {} },
      'Watch Live History': { WatchLiveMap: {} },
      'Watch Live Settings': {
        WatchLiveSettingsMap: { app: '', web: '' },
        MostRecentModificationTimeInApp: '',
        MostRecentModificationTimeInWeb: '',
      },
    },
    'TikTok Shop': {
      'Communication With Shops': { CommunicationHistories: null },
      'Current Payment Information': { PayCard: null },
      'Customer Support History': { CustomerSupportHistories: null },
      'Order Dispute History': { OrderDisputeHistories: null },
      'Order History': { OrderHistories: null },
      'Product Browsing History': { ProductBrowsingHistories: null },
      'Product Reviews': { ProductReviewHistories: null },
      'Returns and Refunds History': { ReturnAndRefundHistories: null },
      'Saved Address Information': { SavedAddress: null },
      'Shopping Cart List': { ShoppingCart: null },
      TikTokFavoriteItem: { TikTokFavoriteItemResult: { TikTokFavoriteItemList: null } },
      Vouchers: { Vouchers: null },
    },
    'Your Activity': {
      'Activity Summary': {
        ActivitySummaryMap: {
          note: '',
          videosCommentedOnSinceAccountRegistration: 0,
          videosSharedSinceAccountRegistration: 0,
          videosWatchedToTheEndSinceAccountRegistration: 0,
        },
      },
      'Ad Interests': { AdInterestCategories: '' },
      'Ads Visit History': { AdsVisitHistoryList: [] },
      Donation: { DonationList: null },
      Fundraiser: { FundraiserList: null },
      Hashtag: { HashtagList: null },
      'Instant Form Ads Responses': { ResponsesList: null },
      'Login History': { LoginHistoryList: [] },
      'Mini Drama Watch History': {},
      'Off TikTok Activity': { OffTikTokActivityDataList: null },
      Purchases: { SendGifts: { SendGifts: null }, BuyGifts: { BuyGifts: null } },
      Reposts: { RepostList: [] },
      Searches: { SearchList: [] },
      'Share History': { ShareHistoryList: null },
      Status: { 'Status List': [] },
      Stickers: { StickerList: null },
      'Watch History': { VideoList: [] },
    },
  };
}
