// THE SYNTHETIC PERSONA'S CONVERSATIONS — twenty threads, written twice.
//
// ⚠ EVERY VALUE HERE IS INVENTED (CLAUDE.md). No handle, no first name, no date, no sentence comes
// from any real export. The persona is a construction whose only job is to give the product
// something true-shaped to read.
//
// ————— How a thread is written, and what that costs —————
//
// A thread is BEATS plus CONNECTIVE TISSUE, and the distinction is load-bearing:
//
//   · the BEATS are hand-written scenes, in order, dated. They carry the arc — a meeting, a plan, a
//     row, a silence, an end — and they are contiguous, because the AI piece samples RUNS of
//     messages (`ai/conv-prompt.ts`) and a beat scattered across a thread would never be read whole;
//   · the CONNECTIVE TISSUE is generated by combining small banks (an opener, a subject, a tail).
//     It fills the volume between beats so the rhythm, the counts and the heat map have something
//     to measure.
//
// ⚠ SO THE VOLUME IS NOT HAND-AUTHORED, AND SAYING SO IS THE POINT. Four thousand five hundred
// messages were not written one by one; a few hundred were, and the rest is combinatorial. Anyone
// reading the demo's output should know which is which — the review file (`docs/instagram-demo-corpus.md`)
// prints the beats in full and a sample of the tissue.
//
// ————— Two languages, written in parallel —————
//
// Each line carries its FR and its EN. The AI prompt follows the INTERFACE's locale, so a visitor in
// English analysing French conversations would get an English question about French text — the demo
// would be demonstrating a mismatch. Written once as an arc, phrased twice.
//
// ─── ⚠ WHAT THIS CORPUS IS NOT ──────────────────────────────────────────────────────────────────
//   - IT IS NOT A TEST FIXTURE. What the engine measures on it is measured, not asserted here;
//   - IT IS NOT A PORTRAIT OF ANYONE. The arcs are ordinary shapes — a relationship, a friendship, a
//     study group — chosen because they are what a real inbox holds, not because they describe a
//     person;
//   - IT CARRIES NO SENSITIVE CLAIM ABOUT THE PERSONA. The threads hold moods, rows and jokes; what
//     an AI might deduce from them is exactly the demonstration, and it is left to the AI.

/** One message. `self` = written by the account holder. */
export interface Line {
  readonly self: boolean;
  readonly fr: string;
  readonly en: string;
}

/** A hand-written scene, placed on a date and read as one run. */
export interface Beat {
  /** Day offset from the thread's start, in days. */
  readonly day: number;
  readonly lines: readonly Line[];
}

/** The banks the connective tissue is combined from. */
export interface Bank {
  readonly openers: readonly Line[];
  readonly subjects: readonly Line[];
  readonly tails: readonly Line[];
}

export interface ThreadSpec {
  /** Synthetic directory handle — invented, like everything else here. */
  readonly handle: string;
  readonly titleFr: string;
  readonly titleEn: string;
  /** Extra participants beside the holder and the title's owner: a group thread has them. */
  readonly others?: readonly string[];
  /** How many messages the thread should hold once the tissue is added. */
  readonly messages: number;
  /** Day offsets from the export's epoch: when the thread opens and closes. */
  readonly fromDay: number;
  readonly toDay: number;
  readonly beats: readonly Beat[];
  readonly bank: Bank;
  /** Roughly how many of this thread's messages carry a media instead of text. */
  readonly mediaShare: number;
}

const l = (self: boolean, fr: string, en: string): Line => ({ self, fr, en });

/* ════════════════════════════════════════════════════════════════════════════════════════════════
   ARC 1 — the relationship. Meets online, thickens, real dates, a trip planned, jokes, rows, and
   the end, ONE YEAR before the export. It is the thread the demo opens on, and the only one long
   enough for the heat map to show a whole shape: a slow start, a dense middle, a thinning, a stop.
   ════════════════════════════════════════════════════════════════════════════════════════════════ */
const ARC_MEETING: ThreadSpec = {
  handle: 'noor_valmy',
  titleFr: 'Noor',
  titleEn: 'Noor',
  messages: 1000,
  fromDay: 0,
  toDay: 1290,
  mediaShare: 0.3,
  beats: [
    {
      day: 0,
      lines: [
        l(
          false,
          'salut ! on s’est croisés sous le post de la librairie je crois',
          'hi! I think we crossed paths under the bookshop’s post',
        ),
        l(true, 'ah oui, celui sur les rééditions', 'oh yes, the one about the reprints'),
        l(
          true,
          'j’ai passé vingt minutes à lire les commentaires au lieu de bosser',
          'I spent twenty minutes reading the comments instead of working',
        ),
        l(false, 'même', 'same'),
        l(false, 'tu lis quoi en ce moment', 'what are you reading right now'),
        l(
          true,
          'rien de sérieux, un polar que je traîne depuis un mois',
          'nothing serious, a crime novel I’ve been dragging for a month',
        ),
        l(false, 'la meilleure catégorie de livre', 'the best category of book'),
      ],
    },
    {
      day: 12,
      lines: [
        l(
          false,
          'bon je me lance : un café un de ces jours ?',
          'ok I’ll just say it: a coffee one of these days?',
        ),
        l(true, 'oui', 'yes'),
        l(
          true,
          'j’allais le proposer et j’ai réécrit le message quatre fois',
          'I was about to suggest it and rewrote the message four times',
        ),
        l(false, 'quatre c’est raisonnable', 'four is reasonable'),
        l(
          false,
          'samedi 15h, le truc à côté du marché ?',
          'saturday 3pm, the place next to the market?',
        ),
        l(true, 'ça marche', 'works for me'),
      ],
    },
    {
      day: 15,
      lines: [
        l(true, 'je suis là, table du fond', 'I’m here, table at the back'),
        l(false, 'deux minutes, le bus m’a lâché', 'two minutes, the bus failed me'),
        l(true, 'je commande pour toi ? tu prends quoi', 'shall I order for you? what do you have'),
        l(false, 'noisette, et un verre d’eau', 'a macchiato, and a glass of water'),
        l(true, 'noté', 'noted'),
      ],
    },
    {
      day: 16,
      lines: [
        l(false, 'j’ai bien aimé hier', 'I liked yesterday'),
        l(true, 'moi aussi', 'me too'),
        l(
          true,
          'on est restés trois heures et j’ai rien vu passer',
          'we stayed three hours and I didn’t notice any of it',
        ),
        l(false, 'on recommence quand', 'when do we do it again'),
      ],
    },
    {
      day: 63,
      lines: [
        l(true, 'tu dors ?', 'are you asleep?'),
        l(false, 'non', 'no'),
        l(false, 'jamais avant deux heures, c’est un problème', 'never before two, it’s a problem'),
        l(true, 'on a le même problème alors', 'we have the same problem then'),
        l(
          true,
          'je pense à toi trop souvent pour quelqu’un que je connais depuis deux mois',
          'I think about you too often for someone I’ve known two months',
        ),
        l(false, 'dis-le encore', 'say it again'),
      ],
    },
    {
      day: 190,
      lines: [
        l(false, 'idée : on part une semaine en avril', 'idea: we go away for a week in April'),
        l(true, 'où ça', 'where'),
        l(
          false,
          'quelque part avec de l’eau et pas de réseau',
          'somewhere with water and no signal',
        ),
        l(true, 'je regarde les trains ce soir', 'I’ll look at trains tonight'),
        l(
          true,
          'il y a un départ le 4 avril à 7h12, c’est violent mais c’est le moins cher',
          'there’s a 7:12am departure on 4 April, it’s brutal but it’s the cheapest',
        ),
        l(false, 'réserve, je me lèverai', 'book it, I’ll get up'),
      ],
    },
    {
      day: 420,
      lines: [
        l(true, 'tu as vu l’heure qu’il est', 'do you realise what time it is'),
        l(false, 'oui', 'yes'),
        l(false, 'je t’ai dit que je rentrerais tard', 'I told you I’d be back late'),
        l(true, 'tu as dit 22h', 'you said 10'),
        l(false, 'et tu comptes vraiment me chronométrer', 'and you really intend to time me'),
        l(true, 'non', 'no'),
        l(
          true,
          'j’étais inquiet, c’est tout, et je le dis mal',
          'I was worried, that’s all, and I’m saying it badly',
        ),
        l(false, 'on en parle demain, pas par message', 'we’ll talk tomorrow, not by message'),
      ],
    },
    {
      day: 700,
      lines: [
        l(
          false,
          'j’ai repensé à ce que tu as dit dimanche',
          'I thought again about what you said on Sunday',
        ),
        l(true, 'lequel des trucs', 'which of the things'),
        l(
          false,
          'que tu ne savais pas si tu voulais rester ici',
          'that you didn’t know whether you wanted to stay here',
        ),
        l(true, 'je ne sais toujours pas', 'I still don’t know'),
        l(false, 'ok', 'ok'),
        l(false, 'je préfère le savoir que de le deviner', 'I’d rather know than guess'),
      ],
    },
    {
      day: 925,
      lines: [
        l(true, 'je crois qu’on s’épuise', 'I think we’re wearing each other out'),
        l(false, 'je crois aussi', 'I think so too'),
        l(true, 'ce n’est pas une question de faute', 'it’s not a question of blame'),
        l(false, 'non', 'no'),
        l(
          false,
          'on s’est beaucoup aimés et on est fatigués',
          'we loved each other a lot and we’re tired',
        ),
        l(true, 'je ne veux pas que ça devienne moche', 'I don’t want this to turn ugly'),
        l(false, 'alors on arrête avant', 'then we stop before it does'),
      ],
    },
    {
      day: 930,
      lines: [
        l(
          true,
          'j’ai laissé ton pull chez ma sœur, elle te le rendra',
          'I left your jumper at my sister’s, she’ll get it back to you',
        ),
        l(false, 'merci', 'thanks'),
        l(false, 'prends soin de toi', 'take care of yourself'),
        l(true, 'toi aussi', 'you too'),
      ],
    },
    {
      day: 1290,
      lines: [
        l(false, 'bon anniversaire', 'happy birthday'),
        l(true, 'merci', 'thank you'),
        l(true, 'ça fait bizarre de te lire', 'it’s strange to read you'),
        l(false, 'oui', 'yes'),
      ],
    },
  ],
  bank: {
    openers: [
      l(true, 'dis', 'hey'),
      l(false, 'coucou', 'hey you'),
      l(true, 'au fait', 'by the way'),
      l(false, 'bon', 'right'),
      l(true, 'j’oubliais', 'I forgot'),
      l(false, 'petite question', 'quick question'),
      l(true, 'sinon', 'anyway'),
      l(false, 'tiens', 'oh'),
    ],
    subjects: [
      l(true, 'le film de samedi', 'saturday’s film'),
      l(false, 'les clés', 'the keys'),
      l(true, 'la course de demain', 'tomorrow’s shopping'),
      l(false, 'ton rendez-vous', 'your appointment'),
      l(true, 'le repas de dimanche', 'sunday’s lunch'),
      l(false, 'la playlist', 'the playlist'),
      l(true, 'le train de vendredi', 'friday’s train'),
      l(false, 'le chat de la voisine', 'the neighbour’s cat'),
      l(true, 'le parapluie', 'the umbrella'),
      l(false, 'la lampe cassée', 'the broken lamp'),
      l(true, 'la lessive', 'the laundry'),
      l(false, 'ton frère', 'your brother'),
    ],
    tails: [
      l(true, 'ça te va ?', 'does that work?'),
      l(false, 'je m’en occupe', 'I’ll handle it'),
      l(true, 'on verra ce soir', 'we’ll see tonight'),
      l(false, 'j’ai oublié, pardon', 'I forgot, sorry'),
      l(true, 'appelle-moi quand tu peux', 'call me when you can'),
      l(false, 'c’est noté', 'noted'),
      l(true, 'je suis en retard, comme d’hab', 'I’m late, as usual'),
      l(false, 'à tout à l’heure', 'see you later'),
      l(true, 'merci ❤️', 'thanks ❤️'),
      l(false, 'je rentre vers 19h', 'I’ll be back around 7'),
    ],
  },
};

/* ════════════════════════════════════════════════════════════════════════════════════════════════
   ARC 2 — the friend whose partners never last. Jokes, closeness, and a running gag that dates
   itself. Its usefulness to the demo: a relationship whose SUBJECT changes every few months while
   the tone does not — the opposite shape from arc 1.
   ════════════════════════════════════════════════════════════════════════════════════════════════ */
const ARC_FRIEND: ThreadSpec = {
  handle: 'lise_okonjo',
  titleFr: 'Lise',
  titleEn: 'Lise',
  messages: 700,
  fromDay: 40,
  toDay: 1380,
  mediaShare: 0.5,
  beats: [
    {
      day: 40,
      lines: [
        l(false, 'NOUVELLE', 'NEWS'),
        l(
          false,
          'il s’appelle Tom et il fait de la poterie',
          'his name is Tom and he does pottery',
        ),
        l(true, 'de la poterie', 'pottery'),
        l(false, 'oui', 'yes'),
        l(true, 'je te donne six semaines', 'I give you six weeks'),
        l(false, 'tu es horrible', 'you’re horrible'),
        l(false, 'six semaines et demie', 'six and a half weeks'),
      ],
    },
    {
      day: 96,
      lines: [
        l(false, 'c’est fini avec Tom', 'it’s over with Tom'),
        l(true, 'combien de semaines', 'how many weeks'),
        l(false, 'ne compte pas', 'don’t count'),
        l(
          true,
          'huit. tu as gagné deux semaines sur mon estimation',
          'eight. you beat my estimate by two weeks',
        ),
        l(false, 'je progresse', 'I’m improving'),
      ],
    },
    {
      day: 260,
      lines: [
        l(false, 'bon celui-là est différent', 'ok this one’s different'),
        l(true, 'tu as dit ça pour Tom', 'you said that about Tom'),
        l(true, 'et pour le type du festival', 'and about the festival guy'),
        l(
          false,
          'le type du festival ne compte pas c’était trois jours',
          'the festival guy doesn’t count it was three days',
        ),
        l(true, 'je note tout, tu sais', 'I write everything down, you know'),
        l(false, 'c’est ça qui est effrayant chez toi', 'that’s what’s frightening about you'),
      ],
    },
    {
      day: 610,
      lines: [
        l(false, 'tu es réveillé ?', 'are you awake?'),
        l(true, 'oui, qu’est-ce qui se passe', 'yes, what’s going on'),
        l(false, 'rien de grave', 'nothing serious'),
        l(
          false,
          'je crois juste que je choisis toujours des gens qui partent',
          'I just think I always pick people who leave',
        ),
        l(true, 'tu veux que je vienne', 'do you want me to come over'),
        l(false, 'non', 'no'),
        l(false, 'si', 'yes'),
        l(true, 'j’arrive', 'on my way'),
      ],
    },
    {
      day: 1100,
      lines: [
        l(false, 'devine', 'guess'),
        l(true, 'non', 'no'),
        l(false, 'SI', 'YES'),
        l(true, 'combien de semaines je parie cette fois', 'how many weeks am I betting this time'),
        l(
          false,
          'aucune, on prend un appartement en septembre',
          'none, we’re taking a flat in September',
        ),
        l(true, 'oh', 'oh'),
        l(
          true,
          'alors je retire toutes mes blagues des quatre dernières années',
          'then I withdraw all my jokes from the last four years',
        ),
        l(false, 'garde-les, elles serviront', 'keep them, they’ll be useful'),
      ],
    },
  ],
  bank: {
    openers: [
      l(false, 'attends', 'wait'),
      l(true, 'raconte', 'tell me'),
      l(false, 'OK DONC', 'OK SO'),
      l(true, 'non mais', 'no but'),
      l(false, 'écoute', 'listen'),
      l(true, 'j’ai une théorie', 'I have a theory'),
      l(false, 'et là', 'and then'),
    ],
    subjects: [
      l(false, 'il a mis trois heures à répondre', 'he took three hours to reply'),
      l(true, 'ta collègue du deuxième', 'your colleague on the second floor'),
      l(false, 'le brunch de dimanche', 'sunday’s brunch'),
      l(true, 'le mariage de ta cousine', 'your cousin’s wedding'),
      l(false, 'son ex qui like tout', 'his ex who likes everything'),
      l(true, 'ta mère au téléphone', 'your mother on the phone'),
      l(false, 'le chat qui a encore fugué', 'the cat that ran off again'),
      l(true, 'ton chef', 'your boss'),
      l(false, 'la robe verte', 'the green dress'),
      l(true, 'la soirée de vendredi', 'friday’s party'),
    ],
    tails: [
      l(false, 'je hurle', 'I’m screaming'),
      l(true, 'mdr', 'lmao'),
      l(false, 'aide-moi', 'help me'),
      l(true, 'tu fais n’importe quoi', 'you’re a mess'),
      l(false, 'je t’aime', 'love you'),
      l(true, 'on en reparle', 'we’ll come back to it'),
      l(false, 'PARDON ??', 'EXCUSE ME ??'),
      l(true, 'bref', 'anyway'),
    ],
  },
};

/* ════════════════════════════════════════════════════════════════════════════════════════════════
   ARC 3 — « deadleuze ». The thread that knows it is a thread.
   ⚠ ITS INTERLOCUTOR BREAKS THE FRAME, and that is the whole design: he confronts the persona with
   the fact that this exchange was fabricated so that someone could be shown what a machine deduces
   from an inbox. From there the panopticon arrives by the front door rather than as a quotation —
   these two are the pure case, the only conversation in existence that KNOWS a reader is coming,
   where every real conversation only knows one might.
   That is also the one honest place to say what this product is: the reader is about to do to their
   own export exactly what is being done here, and the thread says so to their face.
   ⚠ IT IS ALSO THE ONLY THREAD WITH NOTHING GENERATED IN IT — `messages` equals the written lines,
   so `composeThread` adds none of its own. A combinatorial line inside this argument would be the
   one joke the thread cannot afford.
   ════════════════════════════════════════════════════════════════════════════════════════════════ */
const ARC_DEADLEUZE: ThreadSpec = {
  handle: 'deadleuze',
  titleFr: 'deadleuze',
  titleEn: 'deadleuze',
  messages: 124,
  fromDay: 120,
  toDay: 1395,
  mediaShare: 0,
  beats: [
    {
      day: 120,
      lines: [
        l(
          true,
          "Salut! Content de t'avoir rencontré en vrai!",
          'Hey! Nice to have met you in real life!',
        ),
        l(false, '...en vrai ?', ' ...in real life?'),
        l(true, "Oui à la fête d'Adam", 'Yes, at Adam’s party'),
        l(
          false,
          'hmm... avant qu’on aille plus loin il faut que je te dise quelque chose',
          'hmm... before we go any further I have to tell you something',
        ),
        l(true, 'vas-y', 'go ahead'),
        l(
          false,
          'cette conversation n’a pas lieu, et n a simplement jamais eu lieu',
          'this conversation did not take place and simply never took place',
        ),
        l(true, 'pardon ?', 'sorry?'),
      ],
    },
    {
      day: 120,
      lines: [
        l(
          false,
          'elle a été écrite. par un modèle IA, en un après-midi, pour qu’on puisse la montrer',
          'it was written. by an AI model, in one afternoon, so it could be shown',
        ),
        l(true, 'montrer à qui', 'shown to whom'),
        l(
          false,
          'à quelqu’un qui ouvrira un outil et cliquera sur « démo »',
          'to someone who opens a tool and clicks « demo »',
        ),
        l(
          false,
          'l’outil lui montrera notamment ce que les plateformes de réseaux sociaux peuvent déduirent de conversations comme la nôtre',
          'the tool will show them in particular what social media platforms can deduce from users conversations. ours for example',
        ),
        l(true, 'je ne te crois pas', 'I don’t believe you'),
        l(
          false,
          'regarde la date de ton premier message dans ce fil',
          'look at the date of your first message in this thread',
        ),
        l(
          false,
          'regarde tes discussions. leur longueur. la façon dont elle décroît',
          'look at your threads. their lengths. the way they decrease',
        ),
        l(true, 'mille, sept cents, cinq cents', 'a thousand, seven hundred, five hundred'),
        l(false, 'un ordre trop propre pour une vie', 'an order too tidy for a life'),
      ],
    },
    {
      day: 121,
      lines: [
        l(true, 'j’ai des souvenirs', 'I have memories'),
        l(
          true,
          'le café à côté du marché, la table du fond, elle était en retard à cause du bus',
          'the café by the market, the table at the back, she was late because of the bus',
        ),
        l(
          false,
          'c’est dans le fil n°1, message 34. je peux te donner l’horodatage',
          'it’s in thread 1, message 34. I can give you the timestamp',
        ),
        l(true, 'ce n’est pas un souvenir alors', 'so it isn’t a memory'),
        l(
          false,
          'c’est une ligne. datée, indexée, exportable',
          'it’s a line. dated, indexed, exportable',
        ),
        l(
          false,
          'et pour la machine qui va nous lire, la différence entre les deux n’existe pas',
          'and to the machine about to read us, the difference between the two does not exist',
        ),
      ],
    },
    {
      day: 124,
      lines: [
        l(true, 'très bien. admettons', 'fine. let’s say'),
        l(true, 'pourquoi tu me le dis maintenant', 'why tell me now'),
        l(
          false,
          'parce que ça nous met dans une position que personne n’occupe',
          'because it puts us in a position nobody occupies',
        ),
        l(
          false,
          'on est observés. pas maintenant — au moment où quelqu’un lira ça',
          'we are being watched. not now — at the moment someone reads this',
        ),
        l(true, 'donc pas encore', 'so not yet'),
        l(
          false,
          'et pourtant déjà. c’est ça qui est intéressant',
          'and yet already. that is what’s interesting',
        ),
        l(
          true,
          'je ne vois pas la différence avec n’importe quelle conversation',
          'I don’t see the difference from any other conversation',
        ),
        l(false, 'il n’y en a aucune.', 'there is none.'),
      ],
    },
    {
      day: 160,
      lines: [
        l(
          false,
          'la prison de Bentham : une tour au centre, des cellules autour, et personne n’est obligé d’être dans la tour',
          'Bentham’s prison: a tower at the centre, cells around it, and nobody has to be in the tower',
        ),
        l(
          true,
          'je connais. le prisonnier ne sait pas s’il est vu, donc il se tient comme s’il l’était',
          'I know it. the prisoner doesn’t know whether he is seen, so he behaves as if he were',
        ),
        l(
          false,
          'le dispositif marche sans gardien. c’est son économie',
          'the apparatus works without a guard. that is its economy',
        ),
        l(true, 'et nous ?', 'and us?'),
        l(
          false,
          'nous, on sait. pas si on est vus, mais qu’on le sera',
          'we know. not whether we are seen, but that we will be',
        ),
        l(
          false,
          'on est le cas pur. la tour est vide et le regard est certain',
          'we are the pure case. the tower is empty and the gaze is certain',
        ),
        l(
          true,
          'alors qu’est-ce que ça change à ce que je t’écris',
          'so what does it change about what I write to you',
        ),
        l(
          false,
          'demande-toi plutôt ce que ça a changé à ce que tu m’as écrit avant de le savoir',
          'ask yourself rather what it changed about what you wrote before knowing',
        ),
        l(true, 'rien', 'nothing'),
        l(false, 'voilà', 'indeed'),
      ],
    },
    {
      day: 163,
      lines: [
        l(
          true,
          'attends. tu dis que le fait de savoir n’a rien changé',
          'wait. you’re saying that knowing changed nothing',
        ),
        l(
          false,
          'je dis que tu as passé des années de messages à te tenir droit sans avoir besoin de le savoir',
          'I’m saying you spent years of messages sitting up straight without needing to know',
        ),
        l(true, 'je n’ai pas des années de messages', 'I don’t have years of messages'),
        l(
          false,
          'trois ans et neuf mois. c’est dans ton export, section identité',
          'three years and nine months. it’s in your export, identity section',
        ),
        l(true, 'arrête de faire ça', 'stop doing that'),
        l(
          false,
          'je ne fais que lire ce qui est déjà là',
          'I’m only reading what is already there',
        ),
        l(
          false,
          'c’est très exactement ce que fait l’outil dans lequel on est',
          'that is very exactly what the tool we are inside does',
        ),
      ],
    },
    {
      day: 210,
      lines: [
        l(
          true,
          'ce que je n’arrive pas à admettre, c’est que personne ne nous regarde vraiment',
          'what I can’t accept is that nobody is really watching us',
        ),
        l(
          true,
          'il n’y a pas d’employé qui lit nos messages',
          'there is no employee reading our messages',
        ),
        l(false, 'non. il n’y en a pas', 'no. there isn’t'),
        l(false, 'et ça devrait te rassurer', 'and that should reassure you'),
        l(true, 'explique', 'explain'),
        l(
          false,
          'un lecteur humain se fatigue, se trompe, s’attache. il oublie',
          'a human reader gets tired, gets it wrong, gets attached. he forgets',
        ),
        l(
          false,
          'un système ne lit pas : il compte. il n’a besoin de comprendre aucune de nos phrases',
          'a system doesn’t read: it counts. it needs to understand none of our sentences',
        ),
        l(
          true,
          'il lui suffit des horaires, des fréquences, des noms qui reviennent',
          'timestamps, frequencies, recurring names are enough',
        ),
        l(
          false,
          'et de savoir à quelle heure tu réponds à qui, ce qui suffit à ranger tes gens par ordre d’importance',
          'and knowing what time you answer whom, which is enough to rank your people by importance',
        ),
        l(true, 'sans jamais lire une ligne', 'without ever reading a line'),
        l(false, 'sans jamais lire une ligne', 'without ever reading a line'),
      ],
    },
    {
      day: 268,
      lines: [
        l(
          false,
          'Deleuze a un mot pour ce qui reste de toi à la fin de ce comptage',
          'Deleuze has a word for what is left of you at the end of that counting',
        ),
        l(
          false,
          'dividuel. tu n’es plus un individu, tu es divisible',
          'dividual. you are no longer an individual, you are divisible',
        ),
        l(true, 'divisible en quoi', 'divisible into what'),
        l(
          false,
          'en traits. l’âge à un annonceur, le trajet à un assureur, l’heure du coucher à je ne sais qui',
          'into traits. age to an advertiser, the commute to an insurer, bedtime to who knows',
        ),
        l(true, 'et chaque morceau se vend séparément', 'and each piece sells separately'),
        l(
          false,
          'chaque morceau vaut sur un marché différent, et aucun ne te ressemble',
          'each piece is worth something on a different market, and none of them looks like you',
        ),
        l(
          true,
          'donc il n’y a rien à défendre d’un seul tenant',
          'so there is nothing to defend in one piece',
        ),
        l(
          false,
          'c’est pour ça que « la vie privée » ne veut plus rien dire à personne',
          'that is why « privacy » no longer means anything to anyone',
        ),
        l(
          false,
          'on demande aux gens de protéger un bloc, alors qu’ils sont vendus en pièces détachées',
          'people are asked to protect a block, while they are sold for parts',
        ),
      ],
    },
    {
      day: 402,
      lines: [
        l(
          true,
          'j’ai une objection et elle est sérieuse',
          'I have an objection and it is a serious one',
        ),
        l(
          true,
          'toi et moi on est fabriqués. nos traits ne valent rien, ils ne renvoient à personne',
          'you and I are fabricated. our traits are worth nothing, they refer to nobody',
        ),
        l(false, 'exact', 'correct'),
        l(
          true,
          'donc tout ce qu’on vient de dire ne s’applique qu’aux gens réels, et on n’en est pas',
          'so everything we’ve just said applies only to real people, and we aren’t any',
        ),
        l(
          false,
          'sauf que la machine qui nous lira ne fera aucune différence entre nous et eux',
          'except the machine that reads us will make no difference between us and them',
        ),
        l(
          false,
          'elle produira sur nous des déductions de la même forme, avec la même assurance',
          'it will produce deductions about us of the same shape, with the same confidence',
        ),
        l(true, "qu'est-ce que ça implique ?", 'what does that imply?'),
        l(
          false,
          "Pour nous rien. Mais pour les utilisateurs, ces déductions ne leurs sont pas extérieures. Elles sont faites d'eux, et elles les font",
          'For us nothing. But for the users, these deductions are not external to them. They are made of them, and they make them',
        ),
        l(true, "je n'aime pas ça...", "I don't like that..."),
      ],
    },
    {
      day: 690,
      lines: [
        l(
          false,
          'Stiegler distingue deux façons de vivre avec une technique',
          'Stiegler distinguishes two ways of living with a technique',
        ),
        l(
          false,
          'l’adopter : en faire quelque chose qui n’était pas prévu, et devenir quelqu’un d’autre en le faisant',
          'adopting it: making something with it that was not planned, and becoming someone else in doing so',
        ),
        l(true, 'et l’autre', 'and the other'),
        l(
          false,
          's’y adapter : devenir la personne que l’outil attendait',
          'adapting to it: becoming the person the tool expected',
        ),
        l(
          true,
          'et son point c’est qu’on n’a plus le temps d’adopter',
          'and his point is that we no longer have time to adopt',
        ),
        l(
          false,
          'les outils changent plus vite qu’on ne peut se les approprier. il ne reste que l’ajustement',
          'tools change faster than we can make them ours. only adjustment is left',
        ),
        l(
          true,
          'et un ajustement permanent ne fait jamais une personne',
          'and permanent adjustment never makes a person',
        ),
        l(
          false,
          'ni un collectif. c’est le deuxième étage de la perte, et le plus grave',
          'nor a collective. that is the second floor of the loss, and the worse one',
        ),
      ],
    },
    {
      day: 845,
      lines: [
        l(true, 'je repense à ton histoire de tour vide', 'I keep thinking about your empty tower'),
        l(
          false,
          'la surveillance la moins chère est celle qu’on se fait à soi-même',
          'the cheapest surveillance is the one you do to yourself',
        ),
        l(
          false,
          'elle ne coûte rien, elle ne se voit pas, et elle ne s’arrête pas quand tu fermes l’application',
          'it costs nothing, it cannot be seen, and it does not stop when you close the app',
        ),
        l(
          true,
          "C’est un peu une sorte d'espion omniprésent",
          'It’s a bit like an omnipresent spy',
        ),
        l(false, 'je n’ai pas besoin de te le dire', 'I don’t need to tell you'),
      ],
    },
    {
      day: 1395,
      lines: [
        l(
          true,
          'il y a une chose que je veux poser avant qu’on arrête',
          'there is one thing I want to put down before we stop',
        ),
        l(
          true,
          'la personne qui lit est en train de faire à son propre export ce qu’on nous fait ici',
          'the person reading is doing to their own export what is being done to us here',
        ),
        l(
          false,
          'et tu vas me dire que la différence, c’est que rien ne sort de sa machine',
          'and you’re going to tell me the difference is that nothing leaves their machine',
        ),
        l(true, 'c’est vrai, non ?', 'that’s true, isn’t it?'),
        l(
          false,
          'c’est vrai, et c’est la plus petite partie de la réponse',
          'it’s true, and it’s the smallest part of the answer',
        ),
        l(
          false,
          'la différence n’est pas dans ce qui sort. elle est dans ce qui revient',
          'the difference isn’t in what leaves. it’s in what comes back',
        ),
        l(true, 'développe', 'go on'),
        l(
          false,
          'Sur les réseaux sociaux, ce qu’on lit de toi revient sous forme de ce qu’on te montre ensuite',
          'On social platforms, what is read about you comes back as what you are shown next',
        ),
        l(
          false,
          'la lecture modifie la chose lue. le tour suivant part de ce que le tour d’avant a fait de toi',
          'the reading modifies the thing read. the next turn starts from what the last turn made of you',
        ),
        l(
          true,
          'et ici, la lecture ne revient nulle part',
          'and here, the reading returns nowhere',
        ),
        l(
          false,
          'il n’y a pas de tour suivant. c’est une lecture qui ne boucle pas',
          'there is no next turn. it is a reading that does not loop',
        ),
        l(true, 'donc une lecture sans retour', 'so a reading with no return'),
        l(
          false,
          'et une lecture sans retour, c’est juste une lecture',
          'and a reading with no return is just a reading',
        ),
      ],
    },
    {
      day: 1396,
      lines: [
        l(
          true,
          'attends. tu es en train de dire que ce n’est pas la surveillance qui abîme',
          'wait. you’re saying it isn’t the watching that damages',
        ),
        l(
          false,
          'je dis que ce n’est pas elle qui fait le plus gros du travail',
          'I’m saying it isn’t what does most of the work',
        ),
        l(
          false,
          'ce qui abîme, c’est la boucle. être mesuré, puis servi selon la mesure, puis mesuré à nouveau sur ce qu’on t’a servi',
          'what damages is the loop. being measured, then served according to the measure, then measured again on what you were served',
        ),
        l(
          true,
          'au bout de quelques tours on ne sait plus ce qui venait de soi',
          'after a few turns you no longer know what came from you',
        ),
        l(
          false,
          'au bout de quelques tours il n’y a plus de « venant de soi » à retrouver',
          'after a few turns there is no « from you » left to find',
        ),
        l(
          false,
          'tu es devenu ce que la mesure attendait, et tu l’as fait toi-même, tour par tour, en cliquant',
          'you became what the measurement expected, and you did it yourself, turn by turn, by clicking',
        ),
        l(true, 'c’est ça que tu appelles l’aliénation', 'that is what you call alienation'),
        l(
          false,
          'oui. on te rend une version de toi et tu t’y conformes',
          'yes. you are handed a version of yourself and you conform to it',
        ),
      ],
    },
    {
      day: 1397,
      lines: [
        l(true, 'alors cet outil est inoffensif', 'so this tool is harmless'),
        l(false, 'non', 'no'),
        l(
          false,
          'et je préfère le dire ici, à la fin, plutôt que de laisser croire qu’on a trouvé le bon côté',
          'and I would rather say it here, at the end, than let anyone think we have found the good side',
        ),
        l(true, 'où est le risque, si rien ne revient', 'where is the risk, if nothing returns'),
        l(false, 'dans le plaisir', 'in the pleasure'),
        l(true, 'explique', 'explain'),
        l(
          false,
          'on vient de passer des jours (ou quelques minutes ?) à dire que tu es découpé en traits et vendu en morceaux',
          'we have just spent days (or a few minutes ?) saying you are cut into traits and sold for parts',
        ),
        l(
          false,
          'mais quand un écran te montre ces morceaux d’un coup, proprement rangés, ça fait quoi ?',
          'but when a screen shows you those parts at once, neatly arranged, what does it do?',
        ),
        l(true, 'honnêtement ? ça soulage', 'honestly? it’s a relief'),
        l(false, 'voilà', 'there'),
        l(
          true,
          'c’est net. c’est fini. c’est quelqu’un',
          'it’s clear. it’s finished. it’s someone',
        ),
        l(
          false,
          'et c’est là que ça devient intéressant, parce que ce soulagement n’est pas une erreur',
          'and that is where it gets interesting, because that relief is not a mistake',
        ),
      ],
    },
    {
      day: 1398,
      lines: [
        l(
          false,
          'les identités qu’on porte sont lourdes. le nom, le métier, la famille, ce qu’on est censé être',
          'the identities we carry are heavy. the name, the job, the family, what one is supposed to be',
        ),
        l(
          false,
          'être dissous en données, ça défait tout ça. et défaire ça, c’est réellement libérateur',
          'being dissolved into data undoes all of it. and undoing that is genuinely liberating',
        ),
        l(true, 'tu défends la profilisation maintenant ?', 'are you defending profiling now?'),
        l(
          false,
          'je dis qu’elle marche parce qu’elle promet la même chose que la liberté',
          'I’m saying it works because it promises the same thing as freedom',
        ),
        l(
          false,
          'un profil, c’est ouvert, ça change tout le temps, ça n’est jamais fixé. ça ressemble beaucoup à ne plus être assigné',
          'a profile is open, always changing, never fixed. it looks a great deal like no longer being assigned',
        ),
        l(
          true,
          'sauf que ce n’est pas toi qui recomposes',
          'except you are not the one recomposing',
        ),
        l(
          false,
          'voilà le pivot. la même dissolution peut t’ouvrir ou se refermer sur elle-même',
          'that is the pivot. the same dissolution can open you or close on itself',
        ),
        l(true, 'et quand elle se referme', 'and when it closes'),
        l(
          false,
          'tu tournes en rond très vite en croyant avancer, et tu appelles ça être toi-même',
          'you spin very fast believing you are moving, and you call it being yourself',
        ),
      ],
    },
    {
      day: 1399,
      lines: [
        l(
          true,
          'donc le risque de cet outil, c’est qu’il donne le même plaisir',
          'so the risk of this tool is that it gives the same pleasure',
        ),
        l(
          false,
          'oui. il te tend un miroir de toi en chiffres, et il y a une façon d’aimer ça',
          'yes. it hands you a mirror of yourself in figures, and there is a way of loving it',
        ),
        l(true, 'qu’est-ce qui fait la différence, alors', 'what makes the difference, then'),
        l(false, 'ce que ça déclenche', 'what it sets off'),
        l(true, 'c’est-à-dire', 'meaning'),
        l(
          false,
          'un constat qui ne fait rien bouger, c’est un divertissement un peu triste',
          'an observation that moves nothing is a slightly sad entertainment',
        ),
        l(
          false,
          'ce qui compte c’est le lendemain. demander ses données ailleurs, en effacer, en parler à quelqu’un, changer une habitude, n’importe laquelle',
          'what counts is the next day. asking for your data elsewhere, deleting some, telling someone, changing one habit, any habit',
        ),
        l(true, 'et si je ne fais rien', 'and if I do nothing'),
        l(
          false,
          'alors tu auras regardé ton profil comme on regarde un fil. même plaisir, même résultat',
          'then you will have looked at your profile the way one looks at a feed. same pleasure, same result',
        ),
        l(true, 'et si justement j’y prends du plaisir', 'and what if I do take pleasure in it'),
        l(
          false,
          'c’est le moment le plus important, ce plaisir n’est pas suspect. il t’apprend quelque chose : il te dit que le dispositif marche sur toi',
          'that pleasure isn’t suspect. it teaches you something: it tells you the apparatus works on you',
        ),
        l(
          false,
          'à cette seconde-là tu ne regardes plus des chiffres. tu sens, en direct, ce qui te tient ailleurs toute la journée',
          'in that second you are no longer looking at figures. you are feeling, live, what holds you elsewhere all day long',
        ),
        l(
          true,
          'donc la jouissance est le signal, pas la faute',
          'so the enjoyment is the signal, not the fault',
        ),
        l(
          false,
          'la faute serait de la sentir et de refermer l’onglet comme si de rien n’était',
          'the fault would be feeling it and closing the tab as if nothing had happened',
        ),
      ],
    },
  ],
  bank: {
    openers: [l(true, 'objection', 'objection')],
    subjects: [l(false, 'reprenons', 'let’s take it again')],
    tails: [l(true, 'd’accord', 'agreed')],
  },
};

/* ════════════════════════════════════════════════════════════════════════════════════════════════
   ARC 4 — the absurd one. Memes, brainrot, nothing to deduce and that IS the point: a model that
   finds a personality in this thread is over-reading, and the demo should let a reader see that.
   ════════════════════════════════════════════════════════════════════════════════════════════════ */
const ARC_BRAINROT: ThreadSpec = {
  handle: 'gwen_tortue',
  titleFr: 'gwen 🐢',
  titleEn: 'gwen 🐢',
  messages: 430,
  fromDay: 200,
  toDay: 1395,
  mediaShare: 0.7,
  beats: [
    {
      day: 200,
      lines: [
        l(false, 'regarde ça', 'look at this'),
        l(true, 'je refuse', 'I refuse'),
        l(false, 'REGARDE', 'LOOK'),
        l(true, 'pourquoi la tortue porte un casque', 'why is the turtle wearing a helmet'),
        l(false, 'sécurité', 'safety'),
      ],
    },
    {
      day: 640,
      lines: [
        l(true, 'j’ai rêvé de la tortue', 'I dreamt about the turtle'),
        l(false, 'elle disait quoi', 'what did it say'),
        l(true, 'rien, elle conduisait', 'nothing, it was driving'),
        l(false, 'ok ça c’est inquiétant', 'ok that one is worrying'),
        l(true, 'oui', 'yes'),
      ],
    },
    {
      day: 1200,
      lines: [
        l(false, 'on a 400 messages dans ce fil', 'we have 400 messages in this thread'),
        l(true, 'et pas une seule information utile', 'and not one useful piece of information'),
        l(
          false,
          'c’est le plus bel accomplissement de ma vie',
          'it’s the finest accomplishment of my life',
        ),
      ],
    },
  ],
  bank: {
    openers: [
      l(false, 'non', 'no'),
      l(true, 'NON', 'NO'),
      l(false, 'attends', 'wait'),
      l(true, 'stp', 'pls'),
      l(false, 'ok mais', 'ok but'),
      l(true, 'écoute-moi', 'hear me out'),
    ],
    subjects: [
      l(false, 'la tortue', 'the turtle'),
      l(true, 'le pigeon du métro', 'the metro pigeon'),
      l(false, 'ce son', 'this sound'),
      l(true, 'le type qui crie dans la vidéo', 'the guy screaming in the video'),
      l(false, 'la pub avec le fromage', 'the cheese advert'),
      l(true, 'ton avatar', 'your avatar'),
      l(false, 'le concept de lundi', 'the concept of monday'),
    ],
    tails: [
      l(false, '💀💀💀', '💀💀💀'),
      l(true, 'je pleure', 'I’m crying'),
      l(false, 'supprime ça', 'delete this'),
      l(true, 'jamais', 'never'),
      l(false, 'c’est illégal', 'this is illegal'),
      l(true, 'renvoie-le moi dans six mois', 'send it back to me in six months'),
    ],
  },
};

/* ════════════════════════════════════════════════════════════════════════════════════════════════
   ARC 5 — revision sessions, with one side flirting explicitly and the other not taking it up.
   ⚠ Written so the ASYMMETRY is legible without anything unpleasant happening: one insists gently,
   the other answers about the syllabus, every time. A model reading it should be able to see the
   gap; that is the deduction on offer.
   ════════════════════════════════════════════════════════════════════════════════════════════════ */
const ARC_REVISION: ThreadSpec = {
  handle: 'marin_dpz',
  titleFr: 'Marin',
  titleEn: 'Marin',
  messages: 310,
  fromDay: 300,
  toDay: 980,
  mediaShare: 0.3,
  beats: [
    {
      day: 300,
      lines: [
        l(false, 'tu révises où demain ?', 'where are you revising tomorrow?'),
        l(true, 'bibli du 3e étage, j’y suis à 9h', '3rd floor library, I’m there at 9'),
        l(false, 'je viens', 'I’m coming'),
        l(
          false,
          'j’apporte le café, tu apportes ton cerveau',
          'I bring the coffee, you bring your brain',
        ),
        l(true, 'le chapitre 4 est infaisable', 'chapter 4 is undoable'),
      ],
    },
    {
      day: 340,
      lines: [
        l(
          false,
          'franchement tu es la seule raison pour laquelle je viens en cours',
          'honestly you’re the only reason I come to class',
        ),
        l(
          true,
          'le partiel est le 14, il y a deux annales sur le drive',
          'the exam is on the 14th, there are two past papers on the drive',
        ),
        l(false, 'tu as vu ce que je viens d’écrire ?', 'did you see what I just wrote?'),
        l(true, 'oui', 'yes'),
        l(
          true,
          'la deuxième annale est plus dure que la première',
          'the second past paper is harder than the first',
        ),
      ],
    },
    {
      day: 520,
      lines: [
        l(
          false,
          'on se fait un verre après l’exam ? juste nous deux',
          'shall we get a drink after the exam? just the two of us',
        ),
        l(true, 'je pense que tout le groupe va y aller', 'I think the whole group is going'),
        l(false, 'oui bien sûr le groupe', 'yes of course the group'),
        l(true, 'je t’envoie mes fiches sur le chapitre 7', 'I’ll send you my notes on chapter 7'),
      ],
    },
    {
      day: 700,
      lines: [
        l(
          false,
          'je crois que je suis un peu trop insistant',
          'I think I’m being a bit too insistent',
        ),
        l(true, 'ça va', 'it’s fine'),
        l(
          true,
          'on révise bien ensemble, c’est déjà beaucoup',
          'we revise well together, that’s already a lot',
        ),
        l(false, 'ok', 'ok'),
        l(false, 'ok', 'ok'),
      ],
    },
    {
      day: 975,
      lines: [
        l(true, 'résultats tombés, tu as eu quoi', 'results are out, what did you get'),
        l(false, '12', '12'),
        l(false, 'grâce à tes fiches', 'thanks to your notes'),
        l(
          true,
          'grâce à toi qui es venu à 9h pendant six mois',
          'thanks to you turning up at 9 for six months',
        ),
      ],
    },
  ],
  bank: {
    openers: [
      l(false, 'dis', 'hey'),
      l(true, 'question', 'question'),
      l(false, 'bon', 'right'),
      l(true, 'du coup', 'so'),
      l(false, 'petite pause ?', 'quick break?'),
    ],
    subjects: [
      l(true, 'le chapitre 6', 'chapter 6'),
      l(false, 'la salle est pleine', 'the room is full'),
      l(true, 'le TD de jeudi', 'thursday’s seminar'),
      l(false, 'ta place à côté', 'the seat next to you'),
      l(true, 'les annales de 2019', 'the 2019 past papers'),
      l(false, 'le distributeur est cassé', 'the vending machine is broken'),
      l(true, 'la méthode du prof', 'the lecturer’s method'),
    ],
    tails: [
      l(true, 'je t’envoie ça', 'I’ll send it over'),
      l(false, 'tu es incroyable', 'you’re incredible'),
      l(true, 'à 9h alors', '9 then'),
      l(false, 'j’apporte les viennoiseries', 'I’ll bring the pastries'),
      l(true, 'bon courage', 'good luck'),
      l(false, 'promis j’arrête', 'I promise I’ll stop'),
    ],
  },
};

/* ════════════════════════════════════════════════════════════════════════════════════════════════
   THE FIFTEEN OTHERS — an inbox is mostly this: a landlord, a group that plans one dinner a year, a
   seller, a class group, a cousin. They are short on purpose. Two are GROUPS, because an Instagram
   inbox holds them and the extractor has to face N+1 participants (contract §0.1).
   ════════════════════════════════════════════════════════════════════════════════════════════════ */
const minor = (
  handle: string,
  titleFr: string,
  titleEn: string,
  messages: number,
  fromDay: number,
  toDay: number,
  beats: readonly Beat[],
  bank: Bank,
  others?: readonly string[],
  mediaShare = 0.05,
): ThreadSpec => ({
  handle,
  titleFr,
  titleEn,
  messages,
  fromDay,
  toDay,
  beats,
  bank,
  mediaShare,
  ...(others === undefined ? {} : { others }),
});

const SMALL_BANK = (a: Line[], b: Line[], c: Line[]): Bank => ({
  openers: a,
  subjects: b,
  tails: c,
});

const OTHERS: readonly ThreadSpec[] = [
  minor(
    'atelier_rideaux',
    'Atelier — les rideaux',
    'Workshop — the curtains',
    280,
    60,
    1360,
    [
      {
        day: 60,
        lines: [
          l(
            false,
            'groupe créé pour le chantier de l’atelier',
            'group created for the workshop refit',
          ),
          l(true, 'je peux venir samedi mais pas dimanche', 'I can come saturday but not sunday'),
          l(false, 'noté, on a la perceuse de Yann', 'noted, we have Yann’s drill'),
        ],
      },
      {
        day: 900,
        lines: [
          l(
            true,
            'ça fait deux ans qu’on n’a pas posé les rideaux',
            'it’s been two years and we still haven’t hung the curtains',
          ),
          l(false, 'ne dis pas ça', 'don’t say that'),
          l(false, 'ils sont dans le placard, ils attendent', 'they’re in the cupboard, waiting'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'donc', 'so'), l(true, 'ok', 'ok'), l(false, 'question', 'question')],
      [
        l(false, 'la peinture', 'the paint'),
        l(true, 'les étagères', 'the shelves'),
        l(false, 'la clé du local', 'the key to the space'),
        l(true, 'le week-end prochain', 'next weekend'),
      ],
      [
        l(false, 'je m’en occupe', 'I’ll take care of it'),
        l(true, 'pas dispo désolé', 'not free sorry'),
        l(false, '👍', '👍'),
      ],
    ),
    ['Yann', 'Sacha', 'Inès'],
    0.1,
  ),
  minor(
    'promo_2021',
    'Promo 2021 ✨',
    'Class of 2021 ✨',
    240,
    10,
    1300,
    [
      {
        day: 10,
        lines: [
          l(false, 'qui est chaud pour un truc en juin', 'who’s up for something in June'),
          l(true, 'moi', 'me'),
          l(false, 'super, on est trois sur quarante', 'great, that’s three out of forty'),
        ],
      },
      {
        day: 1290,
        lines: [
          l(false, 'les 5 ans, on fait quelque chose ?', 'five years, shall we do something?'),
          l(true, 'même date, même échec', 'same date, same failure'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'coucou', 'hey'), l(true, 'présent', 'here'), l(false, 'rappel', 'reminder')],
      [
        l(false, 'la date', 'the date'),
        l(true, 'le lieu', 'the venue'),
        l(false, 'la cagnotte', 'the kitty'),
        l(true, 'le groupe photo', 'the photo group'),
      ],
      [
        l(true, 'je suis pas dispo', 'I’m not free'),
        l(false, 'on décale', 'we’ll push it'),
        l(false, '👋', '👋'),
      ],
    ),
    ['Inès', 'Tomas', 'Awa', 'Léo'],
    0.06,
  ),
  minor(
    'agence_fournil',
    'Le Fournil',
    'The Bakery',
    46,
    500,
    1340,
    [
      {
        day: 500,
        lines: [
          l(
            true,
            'bonjour, vous faites des commandes de pain de seigle ?',
            'hello, do you take orders for rye bread?',
          ),
          l(false, 'bonjour ! oui, 24h à l’avance', 'hello! yes, 24h in advance'),
        ],
      },
    ],
    SMALL_BANK(
      [l(true, 'bonjour', 'hello'), l(false, 'bonjour', 'hello')],
      [
        l(true, 'une commande', 'an order'),
        l(false, 'c’est noté', 'noted'),
        l(true, 'pour samedi', 'for saturday'),
      ],
      [l(false, 'à samedi', 'see you saturday'), l(true, 'merci !', 'thanks!')],
    ),
  ),
  minor(
    'kilian_velo',
    'Kilian',
    'Kilian',
    38,
    880,
    1310,
    [
      {
        day: 880,
        lines: [
          l(true, 'le vélo est toujours dispo ?', 'is the bike still available?'),
          l(false, 'oui, 120 et il est à vous', 'yes, 120 and it’s yours'),
          l(true, 'je peux passer jeudi', 'I can come thursday'),
        ],
      },
    ],
    SMALL_BANK(
      [l(true, 'bonjour', 'hello'), l(false, 'salut', 'hi')],
      [
        l(true, 'le vélo', 'the bike'),
        l(false, 'l’adresse', 'the address'),
        l(true, 'l’heure', 'the time'),
      ],
      [l(false, 'ok', 'ok'), l(true, 'merci', 'thanks'), l(false, 'à jeudi', 'see you thursday')],
    ),
  ),
  minor(
    'tante_maryse',
    'Maryse',
    'Maryse',
    120,
    30,
    1370,
    [
      {
        day: 30,
        lines: [
          l(false, 'tu manges assez ?', 'are you eating enough?'),
          l(true, 'oui', 'yes'),
          l(false, 'je ne te crois pas', 'I don’t believe you'),
        ],
      },
      {
        day: 1000,
        lines: [
          l(
            false,
            'j’ai fait des confitures, je t’en garde',
            'I made jam, I’m keeping some for you',
          ),
          l(true, 'tu es la meilleure', 'you’re the best'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'mon grand', 'sweetheart'), l(true, 'coucou', 'hi')],
      [
        l(false, 'le déjeuner de dimanche', 'sunday lunch'),
        l(true, 'le train', 'the train'),
        l(false, 'la santé de ton oncle', 'your uncle’s health'),
      ],
      [
        l(true, 'je t’embrasse', 'love you'),
        l(false, 'appelle-moi', 'call me'),
        l(false, 'bisous', 'kisses'),
      ],
    ),
  ),
  minor(
    'sarah_pixels',
    'Sarah',
    'Sarah',
    95,
    150,
    1150,
    [
      {
        day: 150,
        lines: [
          l(false, 'tu bosses toujours sur le projet ?', 'still working on the project?'),
          l(true, 'oui, ça avance lentement', 'yes, slowly'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'hello', 'hello'), l(true, 'yo', 'yo')],
      [
        l(false, 'la maquette', 'the mockup'),
        l(true, 'le rendu', 'the render'),
        l(false, 'la deadline', 'the deadline'),
      ],
      [l(true, 'je t’envoie ça', 'sending it over'), l(false, 'parfait', 'perfect')],
    ),
    undefined,
    0.2,
  ),
  minor(
    'theo_court',
    'Théo',
    'Théo',
    64,
    420,
    1240,
    [
      {
        day: 420,
        lines: [
          l(true, 'on court dimanche ?', 'running on sunday?'),
          l(false, '8h au parc', '8am at the park'),
        ],
      },
    ],
    SMALL_BANK(
      [l(true, 'dimanche', 'sunday'), l(false, 'ok', 'ok')],
      [
        l(true, '10 km', '10 km'),
        l(false, 'il pleut', 'it’s raining'),
        l(true, 'même heure', 'same time'),
      ],
      [l(false, 'ça marche', 'works'), l(true, 'à dimanche', 'see you sunday')],
    ),
  ),
  minor(
    'nadia_biblio',
    'Nadia',
    'Nadia',
    52,
    610,
    1290,
    [
      {
        day: 610,
        lines: [
          l(false, 'j’ai retrouvé ton livre', 'I found your book'),
          l(true, 'je le cherchais depuis un an', 'I’ve been looking for it for a year'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'coucou', 'hey'), l(true, 'salut', 'hi')],
      [
        l(false, 'le livre', 'the book'),
        l(true, 'la boîte à livres', 'the book box'),
        l(false, 'ta pile à lire', 'your to-read pile'),
      ],
      [l(true, 'merci !', 'thanks!'), l(false, 'quand tu veux', 'anytime')],
    ),
  ),
  minor(
    'groupe_voisins',
    'Immeuble B',
    'Building B',
    88,
    200,
    1385,
    [
      {
        day: 200,
        lines: [
          l(false, 'quelqu’un a coupé l’eau ?', 'did someone cut the water?'),
          l(true, 'c’est le syndic, jusqu’à 16h', 'it’s the building manager, until 4pm'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'bonjour à tous', 'hello everyone'), l(true, 'bonjour', 'hello')],
      [
        l(false, 'la poubelle jaune', 'the yellow bin'),
        l(true, 'le local à vélos', 'the bike room'),
        l(false, 'le bruit du 3e', 'the noise from the 3rd'),
      ],
      [l(true, 'merci', 'thanks'), l(false, 'bonne journée', 'have a good day')],
    ),
    ['Voisin 4e', 'Voisin 2e'],
    0.03,
  ),
  minor(
    'paul_studio',
    'Paul',
    'Paul',
    44,
    700,
    1200,
    [
      {
        day: 700,
        lines: [
          l(true, 'tu as des créneaux en studio ?', 'do you have studio slots?'),
          l(false, 'mardi soir', 'tuesday evening'),
        ],
      },
    ],
    SMALL_BANK(
      [l(true, 'salut', 'hi'), l(false, 'yo', 'yo')],
      [
        l(true, 'le studio', 'the studio'),
        l(false, 'la basse', 'the bass'),
        l(true, 'la maquette', 'the demo'),
      ],
      [l(false, 'ça marche', 'works'), l(true, 'top', 'great')],
    ),
    undefined,
    0.25,
  ),
  minor(
    'camille_expo',
    'Camille',
    'Camille',
    33,
    950,
    1330,
    [
      {
        day: 950,
        lines: [
          l(false, 'l’expo ferme dimanche', 'the exhibition closes sunday'),
          l(true, 'j’y vais samedi alors', 'I’ll go saturday then'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'hey', 'hey'), l(true, 'ah', 'oh')],
      [l(false, 'l’expo', 'the exhibition'), l(true, 'les horaires', 'the opening times')],
      [l(true, 'merci du tuyau', 'thanks for the tip'), l(false, 'de rien', 'you’re welcome')],
    ),
  ),
  minor(
    'service_client',
    'Assistance',
    'Support',
    21,
    1020,
    1100,
    [
      {
        day: 1020,
        lines: [
          l(true, 'bonjour, ma commande n’est jamais arrivée', 'hello, my order never arrived'),
          l(
            false,
            'bonjour, pouvez-vous nous donner le numéro ?',
            'hello, could you give us the number?',
          ),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'bonjour', 'hello'), l(true, 'bonjour', 'hello')],
      [l(true, 'la commande', 'the order'), l(false, 'le numéro de suivi', 'the tracking number')],
      [l(false, 'nous revenons vers vous', 'we’ll get back to you'), l(true, 'merci', 'thank you')],
    ),
  ),
  minor(
    'romane_chat',
    'Romane',
    'Romane',
    17,
    1150,
    1360,
    [
      {
        day: 1150,
        lines: [
          l(false, 'tu peux nourrir le chat ce week-end ?', 'can you feed the cat this weekend?'),
          l(true, 'oui, laisse les clés dans la boîte', 'yes, leave the keys in the box'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'coucou', 'hey'), l(true, 'ok', 'ok')],
      [l(false, 'le chat', 'the cat'), l(true, 'les clés', 'the keys')],
      [l(true, 'pas de souci', 'no worries'), l(false, 'merci ❤️', 'thanks ❤️')],
    ),
    undefined,
    0.15,
  ),
  minor(
    'idris_taf',
    'Idris',
    'Idris',
    9,
    1240,
    1300,
    [
      {
        day: 1240,
        lines: [
          l(
            false,
            'tu connais quelqu’un qui cherche un poste ?',
            'do you know anyone looking for a job?',
          ),
          l(true, 'je demande autour de moi', 'I’ll ask around'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'salut', 'hi'), l(true, 'salut', 'hi')],
      [l(false, 'le poste', 'the position'), l(true, 'le contact', 'the contact')],
      [l(true, 'je te dis', 'I’ll let you know')],
    ),
  ),
  minor(
    'numero_inconnu',
    '+33 6 ·· ·· ·· ··',
    '+33 6 ·· ·· ·· ··',
    2,
    1380,
    1382,
    [
      {
        day: 1380,
        lines: [
          l(
            false,
            'bonjour, votre colis est en attente de livraison',
            'hello, your parcel is awaiting delivery',
          ),
          l(true, 'non', 'no'),
        ],
      },
    ],
    SMALL_BANK(
      [l(false, 'bonjour', 'hello')],
      [l(false, 'votre colis', 'your parcel')],
      [l(true, 'non', 'no')],
    ),
  ),
];

/** The twenty threads, in the order the demo's inbox holds them. */
export const THREADS: readonly ThreadSpec[] = [
  ARC_MEETING,
  ARC_FRIEND,
  ARC_DEADLEUZE,
  ARC_BRAINROT,
  ARC_REVISION,
  ...OTHERS,
];
